---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: false

verifier:
  name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[tomcat::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
